spring:
    application:
        name: newfiber-workflow
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    activiti:
        database-schema-update: true
        check-process-definitions: false
        history-level: full
        async-executor-activate: false
